project:
  type: book

book:
  title: "Oficina TRI - Quem Sabe, Ensina 2025"
  author: "Alexandre Jaloto"
  date: "09/24/2025"
  chapters:
    - index.qmd
    - fipc1.qmd
    - fipc2.qmd
    - montagem.qmd
format:
  html:
    theme: cosmo
